version: "3"

services:
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: docker/Fpm.Production.Dockerfile
    working_dir: /var/www/html/dockerapps/laravel-docker-boilerplate
    volumes:
      - .:/var/www/html/dockerapps/laravel-docker-boilerplate
    links:
      - db
    networks:
      - mynet
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraapp
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - mynet
#Volumes
volumes:
  dbdata:
    driver: local
#Docker Networks
networks:
  mynet:
    driver: bridge
