version: "3"

services:
  nginx:
    container_name: mynginx
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8081:80
    volumes:
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html/lara-app
    links:
      - app
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    working_dir: /var/www/html/lara-app
    volumes:
      - .:/var/www/html/lara-app
    links:
      - db
  db:
    image: mysql:5.7
    container_name: laramysql
    volumes:
      - mysqldata:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laraapp
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: 123456
#Volumes
volumes:
  mysqldata:
    driver: local
