version: "3"

services:
  #Laravel App
  app:
    container_name: myapp
    build:
      context: .
      dockerfile: docker/Fpm.Production.Dockerfile
    environment:
      MYSQL_DATABASE: laraapp
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravel
      MYSQL_HOST: db
    working_dir: /var/www/html/lara-app
    volumes:
      - .:/var/www/html/lara-app
    links:
      - db
    networks:
      - mynet

  #Nginx Service
  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www/html/lara-app
      - ./docker/sites/laravel.conf:/etc/nginx/conf.d/
    networks:
      - mynet

  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laraapp
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - mynet

#Docker Networks
networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
